// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: agent/v1/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One-time JWT registration token generated by the dashboard.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Human-readable name chosen by the user for this cluster.
	ClusterName string `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	// Information about the cluster collected by the agent at startup.
	ClusterInfo   *ClusterInfo `protobuf:"bytes,3,opt,name=cluster_info,json=clusterInfo,proto3" json:"cluster_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *RegisterRequest) GetClusterInfo() *ClusterInfo {
	if x != nil {
		return x.ClusterInfo
	}
	return nil
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique cluster ID assigned by the dashboard (UUID).
	ClusterId string `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Permanent agent credential (long-lived JWT) for future Stream calls.
	AgentToken    string `protobuf:"bytes,2,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RegisterResponse) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

// AgentMessage is sent from the agent to the dashboard.
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_K8SResponse
	//	*AgentMessage_WatchEvent
	//	*AgentMessage_Pong
	//	*AgentMessage_ClusterInfo
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetK8SResponse() *K8SResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_K8SResponse); ok {
			return x.K8SResponse
		}
	}
	return nil
}

func (x *AgentMessage) GetWatchEvent() *WatchEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_WatchEvent); ok {
			return x.WatchEvent
		}
	}
	return nil
}

func (x *AgentMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *AgentMessage) GetClusterInfo() *ClusterInfo {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ClusterInfo); ok {
			return x.ClusterInfo
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_K8SResponse struct {
	K8SResponse *K8SResponse `protobuf:"bytes,1,opt,name=k8s_response,json=k8sResponse,proto3,oneof"`
}

type AgentMessage_WatchEvent struct {
	WatchEvent *WatchEvent `protobuf:"bytes,2,opt,name=watch_event,json=watchEvent,proto3,oneof"`
}

type AgentMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,3,opt,name=pong,proto3,oneof"`
}

type AgentMessage_ClusterInfo struct {
	ClusterInfo *ClusterInfo `protobuf:"bytes,4,opt,name=cluster_info,json=clusterInfo,proto3,oneof"`
}

func (*AgentMessage_K8SResponse) isAgentMessage_Payload() {}

func (*AgentMessage_WatchEvent) isAgentMessage_Payload() {}

func (*AgentMessage_Pong) isAgentMessage_Payload() {}

func (*AgentMessage_ClusterInfo) isAgentMessage_Payload() {}

// DashboardMessage is sent from the dashboard to the agent.
type DashboardMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DashboardMessage_K8SRequest
	//	*DashboardMessage_WatchSubscribe
	//	*DashboardMessage_WatchUnsubscribe
	//	*DashboardMessage_Ping
	Payload       isDashboardMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardMessage) Reset() {
	*x = DashboardMessage{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardMessage) ProtoMessage() {}

func (x *DashboardMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardMessage.ProtoReflect.Descriptor instead.
func (*DashboardMessage) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *DashboardMessage) GetPayload() isDashboardMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DashboardMessage) GetK8SRequest() *K8SRequest {
	if x != nil {
		if x, ok := x.Payload.(*DashboardMessage_K8SRequest); ok {
			return x.K8SRequest
		}
	}
	return nil
}

func (x *DashboardMessage) GetWatchSubscribe() *WatchSubscribe {
	if x != nil {
		if x, ok := x.Payload.(*DashboardMessage_WatchSubscribe); ok {
			return x.WatchSubscribe
		}
	}
	return nil
}

func (x *DashboardMessage) GetWatchUnsubscribe() *WatchUnsubscribe {
	if x != nil {
		if x, ok := x.Payload.(*DashboardMessage_WatchUnsubscribe); ok {
			return x.WatchUnsubscribe
		}
	}
	return nil
}

func (x *DashboardMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*DashboardMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isDashboardMessage_Payload interface {
	isDashboardMessage_Payload()
}

type DashboardMessage_K8SRequest struct {
	K8SRequest *K8SRequest `protobuf:"bytes,1,opt,name=k8s_request,json=k8sRequest,proto3,oneof"`
}

type DashboardMessage_WatchSubscribe struct {
	WatchSubscribe *WatchSubscribe `protobuf:"bytes,2,opt,name=watch_subscribe,json=watchSubscribe,proto3,oneof"`
}

type DashboardMessage_WatchUnsubscribe struct {
	WatchUnsubscribe *WatchUnsubscribe `protobuf:"bytes,3,opt,name=watch_unsubscribe,json=watchUnsubscribe,proto3,oneof"`
}

type DashboardMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

func (*DashboardMessage_K8SRequest) isDashboardMessage_Payload() {}

func (*DashboardMessage_WatchSubscribe) isDashboardMessage_Payload() {}

func (*DashboardMessage_WatchUnsubscribe) isDashboardMessage_Payload() {}

func (*DashboardMessage_Ping) isDashboardMessage_Payload() {}

type K8SRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique request ID to correlate with the response.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// HTTP method: GET, POST, PUT, PATCH, DELETE.
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Kubernetes API path, e.g. /api/v1/namespaces/default/pods.
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Optional request body (JSON).
	Body []byte `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	// Optional HTTP headers to forward.
	Headers map[string]string `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional query parameters.
	QueryParams   map[string]string `protobuf:"bytes,6,rep,name=query_params,json=queryParams,proto3" json:"query_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SRequest) Reset() {
	*x = K8SRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SRequest) ProtoMessage() {}

func (x *K8SRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SRequest.ProtoReflect.Descriptor instead.
func (*K8SRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *K8SRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *K8SRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *K8SRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *K8SRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *K8SRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *K8SRequest) GetQueryParams() map[string]string {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

type K8SResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matches K8sRequest.request_id.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// HTTP status code from the Kubernetes API.
	StatusCode int32 `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// Response body (JSON).
	Body []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// Response headers.
	Headers map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Error message if the request could not be executed locally.
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SResponse) Reset() {
	*x = K8SResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SResponse) ProtoMessage() {}

func (x *K8SResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SResponse.ProtoReflect.Descriptor instead.
func (*K8SResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *K8SResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *K8SResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *K8SResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *K8SResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *K8SResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WatchSubscribe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique watch ID.
	WatchId string `protobuf:"bytes,1,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	// Kubernetes API path for the watch, e.g. /api/v1/namespaces/default/pods.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Resource version to start watching from (empty = from now).
	ResourceVersion string `protobuf:"bytes,3,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchSubscribe) Reset() {
	*x = WatchSubscribe{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSubscribe) ProtoMessage() {}

func (x *WatchSubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSubscribe.ProtoReflect.Descriptor instead.
func (*WatchSubscribe) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *WatchSubscribe) GetWatchId() string {
	if x != nil {
		return x.WatchId
	}
	return ""
}

func (x *WatchSubscribe) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WatchSubscribe) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

type WatchUnsubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WatchId       string                 `protobuf:"bytes,1,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchUnsubscribe) Reset() {
	*x = WatchUnsubscribe{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchUnsubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchUnsubscribe) ProtoMessage() {}

func (x *WatchUnsubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchUnsubscribe.ProtoReflect.Descriptor instead.
func (*WatchUnsubscribe) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *WatchUnsubscribe) GetWatchId() string {
	if x != nil {
		return x.WatchId
	}
	return ""
}

type WatchEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the watch this event belongs to.
	WatchId string `protobuf:"bytes,1,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	// Event type: ADDED, MODIFIED, DELETED, ERROR.
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// The Kubernetes object as JSON.
	Object        []byte `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *WatchEvent) GetWatchId() string {
	if x != nil {
		return x.WatchId
	}
	return ""
}

func (x *WatchEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *WatchEvent) GetObject() []byte {
	if x != nil {
		return x.Object
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *Ping) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *Pong) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ClusterInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kubernetes server version (e.g. "v1.28.3").
	KubernetesVersion string `protobuf:"bytes,1,opt,name=kubernetes_version,json=kubernetesVersion,proto3" json:"kubernetes_version,omitempty"`
	// Platform (e.g. "linux/amd64").
	Platform string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	// Number of nodes in the cluster.
	NodeCount int32 `protobuf:"varint,3,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	// List of namespace names.
	Namespaces []string `protobuf:"bytes,4,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	// List of installed CRD names.
	Crds []string `protobuf:"bytes,5,rep,name=crds,proto3" json:"crds,omitempty"`
	// Agent binary version.
	AgentVersion  string `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterInfo) Reset() {
	*x = ClusterInfo{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfo) ProtoMessage() {}

func (x *ClusterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfo.ProtoReflect.Descriptor instead.
func (*ClusterInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ClusterInfo) GetKubernetesVersion() string {
	if x != nil {
		return x.KubernetesVersion
	}
	return ""
}

func (x *ClusterInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ClusterInfo) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *ClusterInfo) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *ClusterInfo) GetCrds() []string {
	if x != nil {
		return x.Crds
	}
	return nil
}

func (x *ClusterInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\fcluster_name\x18\x02 \x01(\tR\vclusterName\x128\n" +
	"\fcluster_info\x18\x03 \x01(\v2\x15.agent.v1.ClusterInfoR\vclusterInfo\"R\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1f\n" +
	"\vagent_token\x18\x02 \x01(\tR\n" +
	"agentToken\"\xf0\x01\n" +
	"\fAgentMessage\x12:\n" +
	"\fk8s_response\x18\x01 \x01(\v2\x15.agent.v1.K8sResponseH\x00R\vk8sResponse\x127\n" +
	"\vwatch_event\x18\x02 \x01(\v2\x14.agent.v1.WatchEventH\x00R\n" +
	"watchEvent\x12$\n" +
	"\x04pong\x18\x03 \x01(\v2\x0e.agent.v1.PongH\x00R\x04pong\x12:\n" +
	"\fcluster_info\x18\x04 \x01(\v2\x15.agent.v1.ClusterInfoH\x00R\vclusterInfoB\t\n" +
	"\apayload\"\x8c\x02\n" +
	"\x10DashboardMessage\x127\n" +
	"\vk8s_request\x18\x01 \x01(\v2\x14.agent.v1.K8sRequestH\x00R\n" +
	"k8sRequest\x12C\n" +
	"\x0fwatch_subscribe\x18\x02 \x01(\v2\x18.agent.v1.WatchSubscribeH\x00R\x0ewatchSubscribe\x12I\n" +
	"\x11watch_unsubscribe\x18\x03 \x01(\v2\x1a.agent.v1.WatchUnsubscribeH\x00R\x10watchUnsubscribe\x12$\n" +
	"\x04ping\x18\x04 \x01(\v2\x0e.agent.v1.PingH\x00R\x04pingB\t\n" +
	"\apayload\"\xee\x02\n" +
	"\n" +
	"K8sRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12;\n" +
	"\aheaders\x18\x05 \x03(\v2!.agent.v1.K8sRequest.HeadersEntryR\aheaders\x12H\n" +
	"\fquery_params\x18\x06 \x03(\v2%.agent.v1.K8sRequest.QueryParamsEntryR\vqueryParams\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10QueryParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf1\x01\n" +
	"\vK8sResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12<\n" +
	"\aheaders\x18\x04 \x03(\v2\".agent.v1.K8sResponse.HeadersEntryR\aheaders\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x0eWatchSubscribe\x12\x19\n" +
	"\bwatch_id\x18\x01 \x01(\tR\awatchId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12)\n" +
	"\x10resource_version\x18\x03 \x01(\tR\x0fresourceVersion\"-\n" +
	"\x10WatchUnsubscribe\x12\x19\n" +
	"\bwatch_id\x18\x01 \x01(\tR\awatchId\"^\n" +
	"\n" +
	"WatchEvent\x12\x19\n" +
	"\bwatch_id\x18\x01 \x01(\tR\awatchId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x16\n" +
	"\x06object\x18\x03 \x01(\fR\x06object\"@\n" +
	"\x04Ping\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"@\n" +
	"\x04Pong\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xd0\x01\n" +
	"\vClusterInfo\x12-\n" +
	"\x12kubernetes_version\x18\x01 \x01(\tR\x11kubernetesVersion\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"node_count\x18\x03 \x01(\x05R\tnodeCount\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x04 \x03(\tR\n" +
	"namespaces\x12\x12\n" +
	"\x04crds\x18\x05 \x03(\tR\x04crds\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion2\x93\x01\n" +
	"\fClusterAgent\x12A\n" +
	"\bRegister\x12\x19.agent.v1.RegisterRequest\x1a\x1a.agent.v1.RegisterResponse\x12@\n" +
	"\x06Stream\x12\x16.agent.v1.AgentMessage\x1a\x1a.agent.v1.DashboardMessage(\x010\x01B6Z4github.com/darkden-lab/argus/backend/pkg/agentpb;agentpbb\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_agent_v1_agent_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: agent.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 1: agent.v1.RegisterResponse
	(*AgentMessage)(nil),          // 2: agent.v1.AgentMessage
	(*DashboardMessage)(nil),      // 3: agent.v1.DashboardMessage
	(*K8SRequest)(nil),            // 4: agent.v1.K8sRequest
	(*K8SResponse)(nil),           // 5: agent.v1.K8sResponse
	(*WatchSubscribe)(nil),        // 6: agent.v1.WatchSubscribe
	(*WatchUnsubscribe)(nil),      // 7: agent.v1.WatchUnsubscribe
	(*WatchEvent)(nil),            // 8: agent.v1.WatchEvent
	(*Ping)(nil),                  // 9: agent.v1.Ping
	(*Pong)(nil),                  // 10: agent.v1.Pong
	(*ClusterInfo)(nil),           // 11: agent.v1.ClusterInfo
	nil,                           // 12: agent.v1.K8sRequest.HeadersEntry
	nil,                           // 13: agent.v1.K8sRequest.QueryParamsEntry
	nil,                           // 14: agent.v1.K8sResponse.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	11, // 0: agent.v1.RegisterRequest.cluster_info:type_name -> agent.v1.ClusterInfo
	5,  // 1: agent.v1.AgentMessage.k8s_response:type_name -> agent.v1.K8sResponse
	8,  // 2: agent.v1.AgentMessage.watch_event:type_name -> agent.v1.WatchEvent
	10, // 3: agent.v1.AgentMessage.pong:type_name -> agent.v1.Pong
	11, // 4: agent.v1.AgentMessage.cluster_info:type_name -> agent.v1.ClusterInfo
	4,  // 5: agent.v1.DashboardMessage.k8s_request:type_name -> agent.v1.K8sRequest
	6,  // 6: agent.v1.DashboardMessage.watch_subscribe:type_name -> agent.v1.WatchSubscribe
	7,  // 7: agent.v1.DashboardMessage.watch_unsubscribe:type_name -> agent.v1.WatchUnsubscribe
	9,  // 8: agent.v1.DashboardMessage.ping:type_name -> agent.v1.Ping
	12, // 9: agent.v1.K8sRequest.headers:type_name -> agent.v1.K8sRequest.HeadersEntry
	13, // 10: agent.v1.K8sRequest.query_params:type_name -> agent.v1.K8sRequest.QueryParamsEntry
	14, // 11: agent.v1.K8sResponse.headers:type_name -> agent.v1.K8sResponse.HeadersEntry
	15, // 12: agent.v1.Ping.timestamp:type_name -> google.protobuf.Timestamp
	15, // 13: agent.v1.Pong.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 14: agent.v1.ClusterAgent.Register:input_type -> agent.v1.RegisterRequest
	2,  // 15: agent.v1.ClusterAgent.Stream:input_type -> agent.v1.AgentMessage
	1,  // 16: agent.v1.ClusterAgent.Register:output_type -> agent.v1.RegisterResponse
	3,  // 17: agent.v1.ClusterAgent.Stream:output_type -> agent.v1.DashboardMessage
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	file_agent_v1_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentMessage_K8SResponse)(nil),
		(*AgentMessage_WatchEvent)(nil),
		(*AgentMessage_Pong)(nil),
		(*AgentMessage_ClusterInfo)(nil),
	}
	file_agent_v1_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*DashboardMessage_K8SRequest)(nil),
		(*DashboardMessage_WatchSubscribe)(nil),
		(*DashboardMessage_WatchUnsubscribe)(nil),
		(*DashboardMessage_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
