version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

  exclusions:
    rules:
      - path: "_test\\.go"
        linters:
          - errcheck

  settings:
    errcheck:
      exclude-functions:
        - encoding/json.Marshal
        - (io.Closer).Close
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-QF*"
