// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: agent/v1/agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterAgent_Register_FullMethodName = "/agent.v1.ClusterAgent/Register"
	ClusterAgent_Stream_FullMethodName   = "/agent.v1.ClusterAgent/Stream"
)

// ClusterAgentClient is the client API for ClusterAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClusterAgent is the gRPC service that agents connect to on the dashboard backend.
type ClusterAgentClient interface {
	// Register is called once by the agent on first connection to exchange
	// a one-time registration token for permanent credentials.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Stream is a long-lived bidirectional stream between dashboard and agent.
	// The dashboard sends requests (K8s API calls, watch subscriptions, pings)
	// and the agent sends back responses, watch events, and pongs.
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, DashboardMessage], error)
}

type clusterAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterAgentClient(cc grpc.ClientConnInterface) ClusterAgentClient {
	return &clusterAgentClient{cc}
}

func (c *clusterAgentClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, ClusterAgent_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterAgentClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, DashboardMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClusterAgent_ServiceDesc.Streams[0], ClusterAgent_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, DashboardMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterAgent_StreamClient = grpc.BidiStreamingClient[AgentMessage, DashboardMessage]

// ClusterAgentServer is the server API for ClusterAgent service.
// All implementations must embed UnimplementedClusterAgentServer
// for forward compatibility.
//
// ClusterAgent is the gRPC service that agents connect to on the dashboard backend.
type ClusterAgentServer interface {
	// Register is called once by the agent on first connection to exchange
	// a one-time registration token for permanent credentials.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Stream is a long-lived bidirectional stream between dashboard and agent.
	// The dashboard sends requests (K8s API calls, watch subscriptions, pings)
	// and the agent sends back responses, watch events, and pongs.
	Stream(grpc.BidiStreamingServer[AgentMessage, DashboardMessage]) error
	mustEmbedUnimplementedClusterAgentServer()
}

// UnimplementedClusterAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterAgentServer struct{}

func (UnimplementedClusterAgentServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedClusterAgentServer) Stream(grpc.BidiStreamingServer[AgentMessage, DashboardMessage]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedClusterAgentServer) mustEmbedUnimplementedClusterAgentServer() {}
func (UnimplementedClusterAgentServer) testEmbeddedByValue()                      {}

// UnsafeClusterAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterAgentServer will
// result in compilation errors.
type UnsafeClusterAgentServer interface {
	mustEmbedUnimplementedClusterAgentServer()
}

func RegisterClusterAgentServer(s grpc.ServiceRegistrar, srv ClusterAgentServer) {
	// If the following call panics, it indicates UnimplementedClusterAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterAgent_ServiceDesc, srv)
}

func _ClusterAgent_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterAgentServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterAgent_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterAgentServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterAgent_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterAgentServer).Stream(&grpc.GenericServerStream[AgentMessage, DashboardMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterAgent_StreamServer = grpc.BidiStreamingServer[AgentMessage, DashboardMessage]

// ClusterAgent_ServiceDesc is the grpc.ServiceDesc for ClusterAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.ClusterAgent",
	HandlerType: (*ClusterAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ClusterAgent_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _ClusterAgent_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent/v1/agent.proto",
}
